apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-wa-manager-deployment
spec:
  selector:
    matchLabels:
      app: ms-wa-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-wa-manager
    spec:
      containers:
        - name: ms-wa-manager
          image: us.gcr.io/digital-hackathon-time-6/ms-wa-manager:0.0.2-SNAPSHOT
          ports:
            - containerPort: 8080